name: Upload Static Report

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  upload-report:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Upload existing report.html as artifact
      uses: actions/upload-artifact@v3
      with:
        name: notebook-output
        path: docs/report.html
